/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

// QueueAllocationReportingStatusApplyConfiguration represents a declarative configuration of the QueueAllocationReportingStatus type for use
// with apply.
//
// QueueAllocationReportingStatus identifies the active fixed-ring allocation cohort.
type QueueAllocationReportingStatusApplyConfiguration struct {
	// RingID identifies the fixed scheduler ring and its accounting domain.
	RingID *string `json:"ringID,omitempty"`
	// RingGeneration identifies the active fixed-ring reporting configuration.
	RingGeneration *string `json:"ringGeneration,omitempty"`
	// ExpectedMembers is the fixed number of reporters in the active cohort.
	ExpectedMembers *int32 `json:"expectedMembers,omitempty"`
}

// QueueAllocationReportingStatusApplyConfiguration constructs a declarative configuration of the QueueAllocationReportingStatus type for use with
// apply.
func QueueAllocationReportingStatus() *QueueAllocationReportingStatusApplyConfiguration {
	return &QueueAllocationReportingStatusApplyConfiguration{}
}

// WithRingID sets the RingID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RingID field is set to the value of the last call.
func (b *QueueAllocationReportingStatusApplyConfiguration) WithRingID(value string) *QueueAllocationReportingStatusApplyConfiguration {
	b.RingID = &value
	return b
}

// WithRingGeneration sets the RingGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RingGeneration field is set to the value of the last call.
func (b *QueueAllocationReportingStatusApplyConfiguration) WithRingGeneration(value string) *QueueAllocationReportingStatusApplyConfiguration {
	b.RingGeneration = &value
	return b
}

// WithExpectedMembers sets the ExpectedMembers field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExpectedMembers field is set to the value of the last call.
func (b *QueueAllocationReportingStatusApplyConfiguration) WithExpectedMembers(value int32) *QueueAllocationReportingStatusApplyConfiguration {
	b.ExpectedMembers = &value
	return b
}
