/*
Copyright The Volcano Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "k8s.io/api/core/v1"
)

// SchedulerAllocationApplyConfiguration represents a declarative configuration of the SchedulerAllocation type for use
// with apply.
//
// SchedulerAllocation is one fixed-ring member's complete Queue allocation snapshot.
type SchedulerAllocationApplyConfiguration struct {
	// RingID identifies the fixed scheduler ring and its accounting domain.
	RingID *string `json:"ringID,omitempty"`
	// RingGeneration is an opaque digest of the fixed-ring reporting configuration.
	RingGeneration *string `json:"ringGeneration,omitempty"`
	// MemberIndex is this reporter's StatefulSet ordinal.
	MemberIndex *int32 `json:"memberIndex,omitempty"`
	// ExpectedMembers is the fixed number of reporters in this ring generation.
	ExpectedMembers *int32 `json:"expectedMembers,omitempty"`
	// Allocated is the complete resource allocation snapshot for this reporter.
	Allocated *v1.ResourceList `json:"allocated,omitempty"`
}

// SchedulerAllocationApplyConfiguration constructs a declarative configuration of the SchedulerAllocation type for use with
// apply.
func SchedulerAllocation() *SchedulerAllocationApplyConfiguration {
	return &SchedulerAllocationApplyConfiguration{}
}

// WithRingID sets the RingID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RingID field is set to the value of the last call.
func (b *SchedulerAllocationApplyConfiguration) WithRingID(value string) *SchedulerAllocationApplyConfiguration {
	b.RingID = &value
	return b
}

// WithRingGeneration sets the RingGeneration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RingGeneration field is set to the value of the last call.
func (b *SchedulerAllocationApplyConfiguration) WithRingGeneration(value string) *SchedulerAllocationApplyConfiguration {
	b.RingGeneration = &value
	return b
}

// WithMemberIndex sets the MemberIndex field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MemberIndex field is set to the value of the last call.
func (b *SchedulerAllocationApplyConfiguration) WithMemberIndex(value int32) *SchedulerAllocationApplyConfiguration {
	b.MemberIndex = &value
	return b
}

// WithExpectedMembers sets the ExpectedMembers field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExpectedMembers field is set to the value of the last call.
func (b *SchedulerAllocationApplyConfiguration) WithExpectedMembers(value int32) *SchedulerAllocationApplyConfiguration {
	b.ExpectedMembers = &value
	return b
}

// WithAllocated sets the Allocated field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Allocated field is set to the value of the last call.
func (b *SchedulerAllocationApplyConfiguration) WithAllocated(value v1.ResourceList) *SchedulerAllocationApplyConfiguration {
	b.Allocated = &value
	return b
}
